# Generated by Django 5.2.7 on 2025-10-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del plan (ej: Plan Básico Mensual)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del plan', null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la donación', max_digits=10)),
                ('periodicidad', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], help_text='Periodicidad del plan', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Si el plan está disponible para captación')),
                ('dia_cobro', models.IntegerField(default=5, help_text='Día del mes para realizar el cobro (1-28)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['periodicidad', 'monto'],
            },
        ),
    ]
