# Generated by Django 5.2.7 on 2025-10-23 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT del cliente (ej: 12345678-9)', max_length=12, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=100)),
                ('email', models.EmailField(help_text='Email del cliente', max_length=254, unique=True)),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=20)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del cliente', null=True)),
                ('fecha_captacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se captó al cliente')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', help_text='Estado actual del cliente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captado_por', models.ForeignKey(help_text='Captador que inscribió al cliente', limit_choices_to={'rol': 'CAPTADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_captados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
