# Generated by Django 5.2.7 on 2025-11-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Activación'), ('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', help_text='Estado actual de la suscripción', max_length=20)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la suscripción')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de finalización (si fue cancelada)', null=True)),
                ('proximo_cobro', models.DateField(help_text='Fecha del próximo cobro programado')),
                ('dia_cobro', models.IntegerField(help_text='Día del mes para realizar el cobro')),
                ('monto_suscrito', models.DecimalField(decimal_places=2, help_text='Monto al que se suscribió (puede diferir del plan actual)', max_digits=10)),
                ('motivo_cancelacion', models.TextField(blank=True, help_text='Motivo de cancelación o pausa', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente suscrito', on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='clientes.cliente')),
                ('plan', models.ForeignKey(help_text='Plan contratado', on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='planes.plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
