# Generated by Django 5.2.7 on 2025-11-05 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREADA', 'Creada'), ('ESTADO', 'Cambio de estado'), ('PLAN', 'Cambio de plan'), ('FECHA', 'Cambio de fecha/día/proximo_cobro'), ('MANDATO', 'Validación de mandato'), ('OTRO', 'Otro')], max_length=20)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_realizados', to=settings.AUTH_USER_MODEL)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='suscripciones.suscripcion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
